Module 3
py4wrds/py4wrds pull request #9
Opened 2024-12-02 22:35 UTC by ajnisbet

* Functions
    * Anatomy of a function
        * Arguments (positional, default, keyword, variable)
        * Returning outputs
        * Variable scope
        * Documenting functionality with docstrings
        * Type annotations
    * Modularization: when to use a function
    * Debugging nested errors with tracebacks
    * Function decorators
    * The functools library
        * Freezing arguments with functools.partial
        * Storing outputs with functools.cache
* Modules
    * Importing code from other modules
    * Module layout
    * Auto-reloading imported modules in jupyter
    * Packages
* Object oriented programing
    * Objects and classes
        * Class syntax
        * Instances vs classes
        * Methods
            * Init
            * __str__
            * Classmethod and staticmethod
        * Property methods
        * When to use classes
        * OOP for data science
    * Dataclasses
        * Constructing dataclasses
        * Dataclasses vs dictionaries
    * Inheritance
        * Overriding functionality
        * Calling super()
        * Extending dataclasses

2024-12-06 17:24 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```python
lake_tahoe_volume_acre_feet = 120_000_000
```
I didn't know that you could put underscores between ints like that! Might want to add a small blurb about that functionality - do you think the right place is when introducing ints in module 2?

2024-12-06 17:26 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```python
def check_number_is_non_negative(num):
    """Throw an error for non-negative numbers."""
```
have not covered errors yet - maybe here is the right spot for the aside?

2024-12-06 17:27 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
To stuff **multiple outputs** in one variable, we can use a tuple
```
I'd call this 'pack' instead of 'stuff', but potato PoTAHto

2024-12-06 17:43 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
### Function decorators
```
I think I'd put this section below the 'when to use functions' section

2024-12-06 17:45 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```python
import functools
import requests

@functools.cache
```
This is mega cool, never knew about it before. Besides loading URLs, is there another motivating example for this? Just trying to contextualize and see whether its worth including - I do think if this also applies to API calls that is very useful and perhaps should be mentioned

2024-12-06 17:46 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
There's a balance to strike here with functions. Not enough functions makes for code that's hard to navigate and prone to bugs. But wrapping every little statement in a function slows development and adds counter-productive complexity.

Here are some suggestions for when it's time to put code in a function:

* To avoid repetition.
  * If you've already written some code to read data from Snowflake, there's no need to re-write that every time in your code that needs snowflake data. Be kind to yourself, make a `read_from_snowflake` function!
  * There's no need to force it though. Sometimes it makes sense to copy and modify code, rather than trying to write a single function that handles two slightly different situations.
* When consistency is needed.
```
a fun. motivating example here is the failure to convert between metric to SI resulting in the mars climate orbiter disaster: https://en.wikipedia.org/wiki/Mars_Climate_Orbiter

2024-12-06 17:48 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
### Library functions

Python comes with a large standard (builtin) library of modules, and the conda environment we installed adds many more. Library modules are accessed using `import`. For example, to use the builtin `statistics` module:
```
maybe mention that we will learn about modules in a little bit!

2024-12-06 17:50 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
Why would you want to crash your code?! Well now when we try to create a bad bounding box, our code fails early (avoiding running code that's doomed to fail), and we get a clear error message about what went wrong, rather than a long traceback triggered in a utility function:
```
great example

2024-12-06 20:32 UTC, kashingtonDC requested changes
epic module 3!!! Left some comments and suggestions

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
### Catching errors

By default, when Python encounters an error, it just gives up and crashes.
```
consider adding something like "and execution of the program stops"

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
### Catching errors

By default, when Python encounters an error, it just gives up and crashes.

When we want Python to continue after an error in some way, we can use the `try` and  `except Exception` keywords. When any code under `try` results in an error, the code under `except` will be run.
```
maybe an example to motivate why we would want to do this? E.g. Error on API call?

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
A common application of this is to perform assertions after loading your data, based on how you expect the data to look, and any assumptions that your model makes about the data.
```
suggest "data types and formats" instead of "how you expect the data to look"

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
The line `super.__init__(lat, lon)` call's the parent's `__init__` method. It's a bit like going `self = Point(lat, lon)`.
```
define parent

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
You can see we've also inherited the `__repr__` method that only displays the coordinated. As an exercise, can you copy the `Point` and `Streamgage` classes, then add a `__repr__` method to `Streamgage` that also displays the id?
```
typo "coordinates"

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown

def cms_to_cfs(flow_cms):
    """Converts flow rate in cubic feet per second to cubic metres per second."""
    flow_cfs = flow_cms * 35.3146662
    return flow_cfs
```

The `import` statement loads *and executes* the module.
```
maybe some description as to what executes means in this context - something like 'now you can call all the functions in the module via dot notation:

2024-12-06 20:32 UTC, kashingtonDC commented on 3-python-fundamentals-ii.ipynb
```markdown
### Import from

You can import individual symbols out of a module.
```
why the use of the word 'symbols'? I prefer 'functions, classes, or class methods'

2024-12-07 00:02 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
I added an explainer blub: I think it's fine to sprinkle non-critical hints like this throughout the course, but feel free to move my blurb to module 2!

2024-12-07 00:18 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Good call, I changed this to a different no-output function that doesn't use errors.

2024-12-07 00:20 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Changed!

2024-12-07 00:26 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Yeah API calls, sql queries, slow functions that read a file from disk and do some processing. I'll add some broader motivation.

2024-12-07 00:31 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Nice, added!

2024-12-07 00:35 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Added a tad more detail, and a tease for the upcoming module coverage

2024-12-07 00:37 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Nice catch, that's what actually matters. Fixed.

2024-12-07 00:40 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
I added a few text examples, and there's a second code example a bit further down that rounds out the motivation I reckon.

2024-12-07 00:46 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
I moved those two examples to their own "what to validate" section and added some more

2024-12-07 00:48 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Good call, missed that bit of assumed knowledge!

2024-12-07 00:50 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Added

2024-12-07 00:50 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
Yep, agreed

2024-12-07 00:54 UTC, ajnisbet commented on 3-python-fundamentals-ii.ipynb
I think it's nice to have all the examples of different function syntax first and together, then wrap up with the when to use section.

To fully lean into that, I moved "When to use functions?" to the very end of the function secion, so it's also below "Type annotations" and "Library functions". Hopefully that makes things more clear?

2024-12-07 00:55 UTC, merged